#########################################################################
# CONFIG FILE FOR RECOVERY OF STICR BARCODES FROM SUB-AMPLIFIED LIBRARY #
#########################################################################

# RESOURCE
THREAD = 24
MEMORY = 256

# PROGRAM PATH
UMI_TOOLS = ""
CUTADAPT = ""
STAR = ""
STAR_INDEX = ""

# WORKING DIRECTORY
RAW_SEQUENCING_DIR = ""
OUTPUT_DIR = ""
WHITELIST_DIR = OUTPUT_DIR + "Step1.Whitelist/"
EXTRACTED_DIR = OUTPUT_DIR + "Step2.Extracted_reads/"
TRIMMED_DIR = OUTPUT_DIR + "Step3.Trimmed_reads/"
ALIGNED_DIR = OUTPUT_DIR + "Step4.Aligned_reads/"
COLLAPSED_DIR = OUTPUT_DIR + "Step5.Collapsed_barcodes/"
COUNT_DIR = OUTPUT_DIR + "Step6.Count_barcodes/"
FILTER_DIR = OUTPUT_DIR + "Step7.Filter_barcodes/"
VALID_DIR = OUTPUT_DIR + "Step8.Valid_barcodes/"

# PARENT LIBRARY (10x Cell Barcodes from Parent Sample)
BARCODE_DIR = ""

# SBATCH
SBATCH_DIR = OUTPUT_DIR + "sbatch/"
def SBATCH(THREAD, MEMORY): return ("#!/bin/bash\n#SBATCH --ntasks=1\n#SBATCH --nodes=1\n#SBATCH --cpus-per-task "+str(THREAD)+"\n#SBATCH --mem="+str(MEMORY)+"G\n#SBATCH --time=2-00:00:00\n#SBATCH --output=%x-%j.out\n\n")

# 10X CHEMISTRY
CHEMISTRY = "SC3Pv3"
if CHEMISTRY == "SC3Pv3": PATTERN = "CCCCCCCCCCCCCCCCNNNNNNNNNNNN" # 28 bp
elif CHEMISTRY == "SC3Pv2": PATTERN = "CCCCCCCCCCCCCCCCNNNNNNNNNN" # 26 bp

# EXPECTED CELL NUMBER {<Sample Name>:<Expected Cell Number>}
EXPECTED_CELL_NUMBER = {}

# STICR PARAMETERS
PRIMER_SEQ = "AGCAAACTGGGGCACAAGC" # 19 bp
PRIMER_SEQ_REV = "CGAACACGGGGTCAAACGA"
PRIMER_SEQ_REV_COMP = "GCTTGTGCCCCAGTTTGCT"

VIRAL_INDEX = "GAATTATCGAATT" # 13 bp (VIRAL INDEX 1)
VIRAL_INDEX_REV = "TTAAGCTATTAAG"
VIRAL_INDEX_REV_COMP = "AATTCGATAATTC"

# STICR READ2 STRUCTURES
# FORWARD: AGCAAACTGGGGCACAAGC GAATTATCGAATT ~ STICR BARCODES ~ 
# REVERSE: ~ STICR BARCODES ~ AATTCGATAATTC GCTTGTGCCCCAGTTTGCT

# THRESHOLD
UMI_THRESHOLD = 5

